### ISSUE TITLE
Can't compile within FlashDevelop

### ISSUE THREAD

**Issue by ghost** [mikechambers/as3corelib#145]
After last update from darronschall (07.11.2010 23:53:15, cc66f99a0d9bfce46b437f51acd16014ba890367), I can't anymore successfully compile any project from Flash Develop without additional setup because of code like this:

if ( token.type == JSON_TOKEN::RIGHT_BRACKET )

FD don't know what is JSON_TOKEN::RIGHT_BRACKET and can't compile it.

**Comment by darronschall** [comment]
Does FlashDevelop provide a way to define compile-time constants used with MXMLC?  In FlashBuilder you can specify additional compiler arguments in the library propject properties in order to build.

A few others have mentioned this as well.  It's a nice optimization but makes it hard for people to use the library as source because of the extra setup steps.

I think the best solution is probably just to revert the change, and I'll create my own fork to include these optimizations.

**Comment by ghost** [comment]
Of course, I could do some extra setup steps to use library, but not everybody can. Sometimes sources could be compiled by non-coders at all (some clients or designers) and there could be a challenge for them to configure IDE and add compile-time constant.

**Comment by darronschall** [comment]
I reverted the compile-time define change out.  The latest source can build without any additional setup required.  Change 24c6c16aecbf0d8fcc043ae671e689b0d4b4c559.

**Comment by ghost** [comment]
Thank you for fast response and fix.
It's all good now.
